import { useState, useEffect, useCallback } from 'react';
import { FileBarChart, Download, Plus, RefreshCw, FileText, Clock } from 'lucide-react';
import { fetchReports, generateReport, downloadReport } from '../api';
import { SectionHeader, Table, Pagination, StatusBadge, Card, ErrorBlock, PageLoader, Spinner, Modal } from '../components/UI';

const REPORT_TYPES = [
  { value: 'revenue',       label: 'Revenue Report' },
  { value: 'services',      label: 'Services Summary' },
  { value: 'users',         label: 'User Activity' },
  { value: 'verifications', label: 'Verifications Log' },
  { value: 'queries',       label: 'Support Queries' },
  { value: 'fleet',         label: 'Fleet Analytics' },
];

const ReportsPage = () => {
  const [data, setData]           = useState([]);
  const [total, setTotal]         = useState(0);
  const [page, setPage]           = useState(1);
  const [loading, setLoading]     = useState(true);
  const [error, setError]         = useState(null);
  const [showGenerate, setShowGen] = useState(false);
  const [downloading, setDl]      = useState(null);
  const limit = 10;

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetchReports({ page, limit });
      setData(res.data || res.reports || []);
      setTotal(res.total || 0);
    } catch (e) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  }, [page]);

  useEffect(() => { load(); }, [load]);

  const handleDownload = async (id, filename) => {
    setDl(id);
    try {
      const res = await downloadReport(id);
      // If backend returns a URL
      if (res.url) {
        const a = document.createElement('a');
        a.href = res.url;
        a.download = filename || `report_${id}.pdf`;
        a.click();
      }
    } catch (e) { alert(e.message); }
    finally { setDl(null); }
  };

  const columns = [
    { key: 'reportId',  label: 'Report ID', render: v => <span className="font-mono text-xs text-gray-500">{v || '—'}</span> },
    { key: 'type',      label: 'Type',      render: v => (
      <span className="flex items-center gap-1.5 text-sm font-semibold text-gray-800">
        <FileText size={13} className="text-red-500" />
        {REPORT_TYPES.find(r => r.value === v)?.label || v}
      </span>
    )},
    { key: 'dateRangeLabel', label: 'Period' },
    { key: 'generatedBy', label: 'Generated By' },
    { key: 'status',    label: 'Status',    render: v => <StatusBadge status={v} /> },
    { key: 'createdAt', label: 'Created',   render: v => v ? new Date(v).toLocaleString() : '—' },
    { key: 'fileSize',  label: 'Size',      render: v => v || '—' },
    { key: '_id',       label: 'Download',  render: (id, row) => (
      row.status === 'completed' ? (
        <button
          onClick={e => { e.stopPropagation(); handleDownload(id || row.id, row.filename); }}
          disabled={downloading === (id || row.id)}
          className="flex items-center gap-1.5 text-xs font-semibold text-red-600 hover:underline disabled:opacity-50"
        >
          {downloading === (id || row.id) ? <Spinner size={12} /> : <Download size={13} />}
          Download
        </button>
      ) : (
        <span className="text-xs text-gray-400 flex items-center gap-1"><Clock size={11} /> Processing</span>
      )
    )},
  ];

  return (
    <div>
      <SectionHeader
        title="Reports"
        subtitle={`${total} generated reports`}
        actions={
          <button
            onClick={() => setShowGen(true)}
            className="flex items-center gap-2 bg-red-600 text-white px-4 py-2.5 rounded-xl text-sm font-semibold hover:bg-red-700 transition-colors shadow-sm"
          >
            <Plus size={16} /> Generate Report
          </button>
        }
      />

      <Card>
        {error ? (
          <ErrorBlock message={error} onRetry={load} />
        ) : (
          <>
            <Table
              columns={columns}
              data={data}
              loading={loading}
              emptyIcon={FileBarChart}
              emptyTitle="No reports yet"
              emptySubtitle="Generate your first report using the button above"
            />
            <Pagination page={page} totalPages={Math.ceil(total / limit)} onPageChange={setPage} />
          </>
        )}
      </Card>

      <GenerateReportModal
        open={showGenerate}
        onClose={() => setShowGen(false)}
        onGenerated={load}
      />
    </div>
  );
};

/* ── Generate Report Modal ──────────────────────────────────── */
const GenerateReportModal = ({ open, onClose, onGenerated }) => {
  const [form, setForm]       = useState({ type: 'revenue', from: '', to: '' });
  const [loading, setLoading] = useState(false);
  const [success, setSuccess] = useState(false);

  const handleGenerate = async () => {
    if (!form.type) return alert('Select a report type');
    if (!form.from || !form.to) return alert('Select a date range');
    if (new Date(form.from) > new Date(form.to)) return alert('Start date must be before end date');

    setLoading(true);
    try {
      await generateReport(form.type, { from: form.from, to: form.to });
      setSuccess(true);
      setTimeout(() => {
        setSuccess(false);
        onClose();
        onGenerated();
      }, 1500);
    } catch (e) { alert(e.message); }
    finally { setLoading(false); }
  };

  return (
    <Modal open={open} onClose={onClose} title="Generate New Report" maxWidth="max-w-md">
      {success ? (
        <div className="flex flex-col items-center justify-center py-8 gap-3">
          <div className="w-14 h-14 rounded-full bg-green-100 flex items-center justify-center">
            <FileBarChart size={28} className="text-green-600" />
          </div>
          <p className="text-base font-bold text-gray-900">Report queued!</p>
          <p className="text-sm text-gray-500">It will be ready for download shortly.</p>
        </div>
      ) : (
        <div className="space-y-5">
          <div>
            <label className="block text-sm font-semibold text-gray-700 mb-2">Report Type</label>
            <div className="grid grid-cols-2 gap-2">
              {REPORT_TYPES.map(rt => (
                <button
                  key={rt.value}
                  type="button"
                  onClick={() => setForm(f => ({ ...f, type: rt.value }))}
                  className={`px-4 py-3 rounded-xl text-sm font-medium border text-left transition-all ${
                    form.type === rt.value
                      ? 'bg-red-600 text-white border-red-600'
                      : 'bg-white text-gray-700 border-gray-200 hover:border-red-300'
                  }`}
                >
                  {rt.label}
                </button>
              ))}
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-2">From Date</label>
              <input
                type="date"
                value={form.from}
                onChange={e => setForm(f => ({ ...f, from: e.target.value }))}
                className="w-full border border-gray-200 rounded-xl px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-red-300"
              />
            </div>
            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-2">To Date</label>
              <input
                type="date"
                value={form.to}
                onChange={e => setForm(f => ({ ...f, to: e.target.value }))}
                className="w-full border border-gray-200 rounded-xl px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-red-300"
              />
            </div>
          </div>

          <div className="p-3 bg-amber-50 border border-amber-200 rounded-xl">
            <p className="text-xs text-amber-700 font-medium">
              Large date ranges may take a few minutes to process. You'll see the report in the list once ready.
            </p>
          </div>

          <button
            onClick={handleGenerate}
            disabled={loading}
            className="w-full flex items-center justify-center gap-2 bg-red-600 text-white py-3 rounded-xl font-semibold text-sm hover:bg-red-700 transition-colors disabled:opacity-50"
          >
            {loading ? <><Spinner size={16} /> Generating…</> : <><RefreshCw size={16} /> Generate Report</>}
          </button>
        </div>
      )}
    </Modal>
  );
};

export default ReportsPage;
