spring.application.name=motomate
spring.mongodb.uri=mongodb://localhost:27017/motomate_db

# Debug logging for web requests
logging.level.web=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG